name: test

on:
  push:
    branches:
      - [ main, developer ]
  pull_request:
    branches:
      - [ main, developer ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci --prefix Back

      - name: Run tests
        run: npm run test --prefix Back
